language: minimal

services:
  - docker

env:
  global:
    - DOCKER_BUILDKIT=1
    - COMPOSE_PARALLEL_LIMIT=2

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build Docker images for each service
  - docker build --memory=8g --memory-swap=8g -t udagram-api-feed ./udagram-api-feed
  - docker build --memory=8g --memory-swap=8g -t reverseproxy ./udagram-reverseproxy
  - docker build --memory=8g --memory-swap=8g -t udagram-frontend ./udagram-frontend
  - docker build --memory=8g --memory-swap=8g -t udagram-api-user ./udagram-api-user


  # Tag Docker images
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v1

  # Push Docker images to DockerHub
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:v1
  - docker push $DOCKER_USERNAME/reverseproxy:v1
